apiVersion: v1
kind: Namespace
metadata:
  name: lukas
  annotations:
    linkerd.io/inject: "enabled"

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: orderapi-grpc-server
  namespace: lukas
  labels:
    name: orderapi-grpc-server
    app: orderapiservice
spec:
  replicas: 2
  selector:
    matchLabels:
      name: orderapi-grpc-server
  template:
    metadata:
      labels:
        name: orderapi-grpc-server
    spec:
      containers:
      - name: orderapi-grpc-server
        image: 053675267868.dkr.ecr.eu-west-1.amazonaws.com/lukas/orderapi-grpc-server
        env:
          - name: STAGE
            value: "dev"
          - name: AWS_REGION
            value: "eu-west-1"
          - name: PORT
            value: "9092"
